-- Migration: open up RSVP matching + per-attendee rsvps storage
--
-- 1. Remove the unique full_name index on guests -- it is now only a
--    lookup/autocomplete roster, not a strict verification gate, so
--    duplicate names (two guests who happen to share a first name,
--    or a plus-one reusing the invitee's own name) are fine.
-- 2. Reload guests from the couple's real list.
-- 3. Reshape rsvps to store one row per ATTENDING PERSON rather than
--    one row per party with a guest_count column -- a party of N
--    becomes N rows sharing the same party_key + submitted_name.

drop index if exists guests_full_name_lower_idx;

delete from rsvps;
delete from guests;

insert into guests (full_name, party_size) values
  ('Aisha', 1),
  ('Mamie Muleka', 1),
  ('Antoinnette Tshikunda', 1),
  ('Blaise kalala', 1),
  ('Bijoux', 1),
  ('Denis Kalala', 1),
  ('Bosebe', 1),
  ('Divin Ilunga', 1),
  ('Mpiangu', 2),
  ('Jenovic Kalenga', 1),
  ('Valentin', 2),
  ('Alice Ntumba', 1),
  ('Elie Bukasa', 2),
  ('John Tshani', 1),
  ('Baron', 2),
  ('Nadine tshani', 1),
  ('Dona', 2),
  ('Johadinne Tshani', 1),
  ('Pierre', 2),
  ('Nathan Tshani', 1),
  ('Paul', 2),
  ('Nathaniel Tshani', 1),
  ('Francis', 2),
  ('Joshua Tshani', 1),
  ('Roge', 2),
  ('Syntiche Mbelu', 1),
  ('Rose', 2),
  ('Blessing Mbelu', 1),
  ('Alain Mavinga', 2),
  ('Gretha', 1),
  ('Peter Nkudulu', 2),
  ('Ma Sido', 1),
  ('Valerio', 2),
  ('Papa luck', 1),
  ('Pr Jean-Claude', 2),
  ('Greg', 1),
  ('Pr Limbaya', 2),
  ('Danny', 1),
  ('Peddy', 2),
  ('Guy Ntumba', 1),
  ('Papy Kiasi', 2),
  ('Joelle Ntumba', 1),
  ('Nouveau', 2),
  ('Alice Ntumba', 1),
  ('Serge Napoleon', 2),
  ('Dan Ntumba', 1),
  ('Vincent Emandjala', 2),
  ('Guy jr Ntumba', 1),
  ('Leontine & Kaddy', 2),
  ('Micheal Ntumba', 1),
  ('Erick Mbombo', 2),
  ('Karaine', 1),
  ('Pr Simon', 2),
  ('Nathan', 1),
  ('Anozy', 2),
  ('Ma Jolie', 1),
  ('Blaise', 2),
  ('Daniella', 1),
  ('Goddard', 2),
  ('Tahlita', 1),
  ('Josue', 2),
  ('Ma Alfo', 1),
  ('Joly', 2),
  ('Ma Alfo husband', 1),
  ('Amede', 2),
  ('Grandpa Tshani', 1),
  ('Lola', 2),
  ('Grandma Alice', 1),
  ('Rodrigue', 2),
  ('Grandpa Denis', 1),
  ('Tresor Nzengu', 2),
  ('Tonton Patrick', 1),
  ('Tresor Muanko', 2),
  ('Pa Thati', 1),
  ('Stanislas', 2),
  ('Ma Betty', 1),
  ('Dr PJ', 2),
  ('pa flore', 1),
  ('Olivier', 2),
  ('Ma Bijoux', 1),
  ('Enoc', 2),
  ('Pa alex family', 1),
  ('Steve & Sabine', 2),
  ('Ma yvete', 1),
  ('Titi', 2),
  ('Ma Nadine friend', 1),
  ('John', 2),
  ('Ma Jackie', 1),
  ('Jean-Paul Kapela', 2),
  ('Grandma Sido kaseka', 1),
  ('Ruben', 2),
  ('Grandma Sido husband', 1),
  ('Patty', 2),
  ('Papa Chris', 1),
  ('Sylvie', 1),
  ('Mama maguy', 1),
  ('George', 1),
  ('Papa Serge church', 1),
  ('Ntita', 2),
  ('Papa Serge church WIFE', 1),
  ('Ntita Fille', 2),
  ('Pastor Eric', 1),
  ('Fama', 1),
  ('Pastor Eric wife', 1),
  ('Pitshou', 1),
  ('mama ygete mwambuyi', 1),
  ('Meddy', 1),
  ('Pastor Patrick and wife', 2),
  ('Costa', 1),
  ('Isaac and his parents', 3),
  ('Farel Ngoy', 1),
  ('Jenerose family', 2),
  ('Emma', 1),
  ('Aristote', 1),
  ('Farel Nkashama', 1),
  ('Ya Jeane family', 4),
  ('Val', 1),
  ('mama Agel and husband', 2),
  ('Sam', 1),
  ('Mama bibiche', 2),
  ('Erick', 1),
  ('Gloria and clark', 2),
  ('Sidonie', 1),
  ('brady and joyce', 3),
  ('Lape', 1),
  ('daniel', 1),
  ('Jeannette', 1),
  ('Diva', 1),
  ('Fannie', 1),
  ('Gloria Tshabola', 2),
  ('Michel', 1),
  ('Dan Tshabola', 2),
  ('Gaston', 1),
  ('Lucy and husband', 2),
  ('Obed', 1),
  ('Tshabola brothers', 2),
  ('Bodry', 1),
  ('cj', 1),
  ('Cedrick', 1),
  ('CJ  mom and dad', 2),
  ('Gerard', 1),
  ('amanda', 1),
  ('Ange', 1),
  ('extra 1', 1),
  ('Bona', 1),
  ('extra 2', 1),
  ('Fabrice', 1),
  ('extra 3', 1),
  ('Sophia', 1),
  ('extra 4', 1),
  ('Barth', 2),
  ('extra 5', 1),
  ('Chantal', 1),
  ('extra 6', 1),
  ('Melina', 1),
  ('extra 7', 1),
  ('Sandra', 1),
  ('extra 8', 1),
  ('Sandrine', 1),
  ('Dyna', 1),
  ('Esther', 1),
  ('Dorcas', 1),
  ('Solange', 1),
  ('Gracia', 1),
  ('Monique Ngandu & Enoc Kabila', 2);

alter table rsvps drop constraint if exists rsvps_guest_id_fkey;
alter table rsvps drop constraint if exists rsvps_guest_id_key;
alter table rsvps drop column if exists guest_id;
alter table rsvps drop column if exists guest_count;
alter table rsvps add column if not exists party_key text;
alter table rsvps alter column party_key set not null;

create index if not exists rsvps_party_key_idx on rsvps (party_key);

update reception_tables set seats_taken = 0;
